### ISSUE TITLE
Entrega del TPO #2

### ISSUE THREAD

**Issue by leomendu** [fiuba-labo-de-micro-miercoles/2020-1c-trabajos-practicos-mendoza#2]
Hola, 

Abro _issue_ para la entrega del TPO #2 que subi ayer, ya corregi cosas generales que se habian marcado en entrega de TPO #1. 

[Informe](https://github.com/fiuba-labo-de-micro-miercoles/2020-1c-trabajos-practicos-mendoza/blob/master/tp2/doc/informes/86_07_tp2_mendoza.pdf)

Saludos.

**Comment by PucciFernando** [comment]
Leonel, algunas observaciones:

1- El diagrama en bloques no muestra que el micro esté alimentado, es sutil, pero viendo eso parece que se alimenta por medio del led y el pulsador.

2- En el circuito 1, sin push-up, que valor tiene el pin PD1 cuando el pulsador está abierto? Se necesita algo más? (pregunta del ejercicio)

3- Lo probaste? - Hay algún video o foto? (relacionado con el punto 2)
Saludos

**Comment by leomendu** [comment]
Hola, gracias por tus comentarios.

1- Tenes razón, no se como no me di cuenta antes. Ya corregí el diagrama.

2- En el circuito sin pull-up, el pin PD1 queda flotando, en principio se supone que ese pin tiene valor 0 (o en su defecto un valor muy bajo), pero para asegurar un 0 sería ideal tener un resistor puesto a tierra, también lo modifiqué y lo agregué al [informe](https://github.com/fiuba-labo-de-micro-miercoles/2020-1c-trabajos-practicos-mendoza/blob/master/tp2/doc/informes/86_07_tp2_mendoza.pdf).

3- Lo probé y funcionó, al parecer no se subió por limites de almacenamiento de git, ahora veo de recortarlo y volver a subirlo.

Saludos.

**Comment by leomendu** [comment]
Demo de los programas del TPO #2

[CON Pull-Up](https://youtu.be/G8VUMBrtfXw)

[SIN Pull-Up](https://youtu.be/RNcxFjp96z4)

**Comment by PucciFernando** [comment]
Bien. Aprobado.
En principio no es bueno suponer nada, y menos en hardware, es mejor poner la resistencia y justamente esa era la idea del TP, darse cuenta que se ahorra un componente.
