### ISSUE TITLE
Corrección de TPO6 y final de la materia

### ISSUE THREAD

**Issue by leomendu** [fiuba-labo-de-micro-miercoles/2020-1c-trabajos-practicos-mendoza#9]
Buenas, el domingo mande un mail a los profesores de la practica consultando el estado de la correccion de mi TPO 6 ya que el viernes tenia pensado rendir final, no recibi respuesta alguna.

Tengo entendido que es necesario tener todos los tps corregidos para rendir final. De no ser así me vendría bien que me lo aclaren.

Gracias.

**Comment by fbaglivo** [comment]
Hola Leo, hable con @pimartos  y me dijo que ya reviso el TP y esta ok. Las actas ya estan actualizadas.

**Comment by leomendu** [comment]
Genial, gracias!
